import "relay/TourGuide_wc/Quests/Level 2.ash";
import "relay/TourGuide_wc/Quests/Level 3.ash";
import "relay/TourGuide_wc/Quests/Level 4.ash";
import "relay/TourGuide_wc/Quests/Level 5.ash";
import "relay/TourGuide_wc/Quests/Level 6.ash";
import "relay/TourGuide_wc/Quests/Level 7.ash";
import "relay/TourGuide_wc/Quests/Level 8.ash";
import "relay/TourGuide_wc/Quests/Level 9.ash";
import "relay/TourGuide_wc/Quests/Level 10.ash";
import "relay/TourGuide_wc/Quests/Level 11.ash";
import "relay/TourGuide_wc/Quests/Level 12.ash";
import "relay/TourGuide_wc/Quests/Level 13.ash";
import "relay/TourGuide_wc/Quests/Manor.ash";
import "relay/TourGuide_wc/Quests/Pirate.ash";
import "relay/TourGuide_wc/Quests/Nemesis.ash";
import "relay/TourGuide_wc/Quests/Sea.ash";
import "relay/TourGuide_wc/Quests/Space Elves.ash";
import "relay/TourGuide_wc/Quests/Azazel.ash";
import "relay/TourGuide_wc/Quests/Untinker.ash";
import "relay/TourGuide_wc/Quests/Artist.ash";
import "relay/TourGuide_wc/Quests/Legendary Beat.ash";
import "relay/TourGuide_wc/Quests/Memories.ash";
import "relay/TourGuide_wc/Quests/White Citadel.ash";
import "relay/TourGuide_wc/Quests/Wizard of Ego.ash";
import "relay/TourGuide_wc/Quests/Spookyraven Lights Out.ash";
import "relay/TourGuide_wc/Quests/Felonia.ash";
import "relay/TourGuide_wc/Quests/Guild.ash";
import "relay/TourGuide_wc/Quests/Airport.ash";
import "relay/TourGuide_wc/Quests/Subject 37.ash";
import "relay/TourGuide_wc/Quests/Marty.ash";
import "relay/TourGuide_wc/Quests/Meatsmith.ash";
import "relay/TourGuide_wc/Quests/Intergalaktik.ash";
import "relay/TourGuide_wc/Quests/Old Landfill.ash";
import "relay/TourGuide_wc/Quests/Madness Bakery.ash";

