name: bundle Guide

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.ash'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - id: info_gathering
        shell: python
        run: |
          import os
          print("current dir: " + os.getcwd())
          print(os.listdir())
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - id: more_info
        run: |
          echo $GITHUB_WORKSPACE
          echo $HOME
        
      - id: bundle
        name: Forward output
        shell: python
        run: |
          import os
          import sys
          # Get out of the '.github' folder (apparently not even needed since execution seems to start on the root folder, but, eh, just in case...)
          while '.github' in os.getcwd(): os.chdir('..')
          
          sys.path.append(os.getcwd())
          import Bundle_ASH_script
          
          # The script that bundles the target script. First argument is the target script. Second argument is the path to reach the file to create/put the result in. Third argument (optional) is the path to reach the "mafia folder".
          Bundle_ASH_script.bundle_and_write('relay/relay_TourGuide.ash', 'Bundled_TourGuide.ash', 'Source')
          
          print(os.listdir())
  #push_to_branch:
    #needs: build
    #runs-on: windows-lastest
