name: bundle Guide

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.ash'

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- uses: actions/setup-node@v1
      #- run: npm init -y
      #- run: npm install @actions/core
      #- run: npm install @actions/github
      
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - id: bundle
        name: Forward output
        #uses: ./.github/actions
        shell: python
        run: |
          import os
          # Get out of the '.github' folder
          while '.github' in os.getcwd(): os.chdir('..')
          
          print(os.environ['PYTHONPATH'])
          os.environ['PYTHONPATH'] = os.environ['PYTHONPATH'] + ';' + os.getcwd()
          print(os.environ['PYTHONPATH'])
          print("current dir: " + os.getcwd())
          print(os.listdir())
          import Bundle_ASH_script
          
          # The script that bundles the target script. First argument is the target script. Second argument is the path to reach the file to create/put the result in. Third argument (optional) is the path to reach the "mafia folder".
          Bundle_ASH_script.bundle_and_write('relay/relay_TourGuide.ash', 'Bundled_TourGuide.ash', 'Source')
      #- run: echo "The time was ${{ steps.bundle.outputs.compiled_output }}"
  #push_to_branch:
    #needs: build
    #runs-on: windows-lastest
